<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template_pages PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<template_pages xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Test Report</title>
    <meta name="generator" content="HTMLTestRunner"/>
    <meta http-equiv="Content-Type" content="text/template_pages; charset=UTF-8"/>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="http://apps.bdimg.com/libs/Chart.js/0.2.0/Chart.min.js"></script>
    <!-- <link href="https://cdn.bootcss.com/echarts/3.8.5/echarts.common.min.js" rel="stylesheet">   -->

    
<style type="text/css" media="screen">
body        { font-family: verdana, arial, helvetica, sans-serif; font-size: 80%; }
table       { font-size: 100%; }
pre         {  }

/* -- heading ---------------------------------------------------------------------- */
h1 {
	font-size: 16pt;
	color: gray;
}
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
	margin-left: 10px;
}

.heading .attribute {
    margin-top: 1ex;
    margin-bottom: 0;
}

.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}

/* -- css div popup ------------------------------------------------------------------------ */
a.popup_link {
}

a.popup_link:hover {
    color: red;
}

.popup_window {
    display: none;
    position: relative;
    left: 0px;
    top: 0px;
    /*border: solid #627173 1px; */
    font-family: "Lucida Console", "Courier New", Courier, monospace;
    text-align: left;
    font-size: 8pt;
    width: 500px;
}

}
/* -- report ------------------------------------------------------------------------ */
#show_detail_line {
    margin-top: 3ex;
    margin-bottom: 1ex;
    margin-left: 10px;
}
#result_table {
    width: 80%;
    border-collapse: collapse;
    border: 1px solid #777;
    margin-left: 10px;
}
#header_row {
    font-weight: bold;
    color: #606060;
    background-color: #f5f5f5;
    border-top-width: 10px;
    border-color: #d6e9c6;
	font-size: 12px;
}
#result_table td {
    border: 1px solid #f5f5f5;
    padding: 2px;

}
#total_row  { font-weight: bold; }
.passClass  { background-color: #d6e9c6; }
.failClass  { background-color: #faebcc; }
.errorClass { background-color: #ebccd1; }
.passCase   { color: #6c6; }
.failCase   { color: #c60; font-weight: bold; }
.errorCase  { color: #c00; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }


/* -- ending ---------------------------------------------------------------------- */
#ending {
}

/* -- chars ---------------------------------------------------------------------- */
.testChars {margin-left: 150px;}

.btn-info1 {
    color: #fff;
    background-color: #d6e9c6;
    border-color: #d6e9c6;
}

.btn-info2 {
    color: #fff;
    background-color: #faebcc;
    border-color: #faebcc;
}

.btn-info3 {
    color: #fff;
    background-color: #ebccd1;
    border-color: #ebccd1;
}
</style>

</head>
<body>
<script language="javascript" type="text/javascript"><!--
output_list = Array();

/* level - 0:Summary; 1:Failed; 2:All */
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level < 1) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level > 1) {
                tr.className = '';
            }
            else {
                tr.className = 'hiddenRow';
            }
        }
    }
}


function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        tid0 = 't' + cid.substr(1) + '.' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        if (toHide) {
            document.getElementById('div_'+tid).style.display = 'none'
            document.getElementById(tid).className = 'hiddenRow';
        }
        else {
            document.getElementById(tid).className = '';
        }
    }
}


function showTestDetail(div_id){
    var details_div = document.getElementById(div_id)
    var displayState = details_div.style.display
    // alert(displayState)
    if (displayState != 'block' ) {
        displayState = 'block'
        details_div.style.display = 'block'
    }
    else {
        details_div.style.display = 'none'
    }
}


function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}

/* obsoleted by detail in <div>
function showOutput(id, name) {
    var w = window.open("", //url
                    name,
                    "resizable,scrollbars,status,width=800,height=450");
    d = w.document;
    d.write("<pre>");
    d.write(html_escape(output_list[id]));
    d.write("\n");
    d.write("<a href='javascript:window.close()'>close</a>\n");
    d.write("</pre>\n");
    d.close();
}
*/
--></script>

<div class='heading'>
<h1>Test Report</h1>
<p class='attribute'><strong>Start Time:</strong> 2022-07-18 03:51:53</p>
<p class='attribute'><strong>Duration:</strong> 0:00:01.781251</p>
<p class='attribute'><strong>Status:</strong> Error 3</p>

<p class='description'>Test Description</p>
</div>

<div style="float:left; margin-left: 10px;">
	<p> Test Case Pie charts </p>
	<a class="btn btn-xs btn-info1">-Pass-</a><br>
	<a class="btn btn-xs btn-info2">-Faild-</a><br>
	<a class="btn btn-xs btn-info3">-Error-</a><br>
</div>

<div class="testChars">
	<canvas id="myChart" width="250" height="250"></canvas>
</div>



<p id='show_detail_line' style="margin-left: 10px;">Show
<a href='javascript:showCase(0)' class="btn btn-xs btn-primary">Summary</a>
<a href='javascript:showCase(1)' class="btn btn-xs btn-danger">Failed</a>
<a href='javascript:showCase(2)' class="btn btn-xs btn-info">All</a>
</p>
<table id='result_table'>
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="panel-title">
    <td>Test Group/Test case_data</td>
    <td>Count</td>
    <td>Pass</td>
    <td>Fail</td>
    <td>Error</td>
    <td>View</td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.TestUsers_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c1',1)">Detail</a></td>
</tr>

<tr id='ft1.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_user</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.1')" >
        error</a>

    <div id='div_ft1.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.1: --- Logging error ---
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 45, in get
    response = requests.get(self.url, headers=self.headers, params=self.data,
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 489, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 1085, in emit
    msg = self.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 929, in format
    return fmt.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 668, in format
    record.message = record.getMessage()
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "D:/Program Files/JetBrains/Projects/pythonProjects/interfaceTest/testCase/runAll.py", line 114, in &lt;module&gt;
    runner.run(suit)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\HTMLTestRunner.py", line 600, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\testCase\django_test\test_users.py", line 30, in test_user
    self.r = ch.get(self.case_name)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 50, in get
    logger.error('用例 %s 请求错误' % case_name, e)
Message: '用例 test_users_auth_error 请求错误'
Arguments: (AttributeError("'str' object has no attribute 'items'"),)
--- Logging error ---
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 45, in get
    response = requests.get(self.url, headers=self.headers, params=self.data,
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 489, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 1085, in emit
    msg = self.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 929, in format
    return fmt.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 668, in format
    record.message = record.getMessage()
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "D:/Program Files/JetBrains/Projects/pythonProjects/interfaceTest/testCase/runAll.py", line 114, in &lt;module&gt;
    runner.run(suit)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\HTMLTestRunner.py", line 600, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\testCase\django_test\test_users.py", line 30, in test_user
    self.r = ch.get(self.case_name)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 50, in get
    logger.error('用例 %s 请求错误' % case_name, e)
Message: '用例 test_users_auth_error 请求错误'
Arguments: (AttributeError("'str' object has no attribute 'items'"),)
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\testCase\django_test\test_users.py", line 31, in test_user
    self.assertIn(str(self.msg), self.r)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 1176, in assertIn
    if member not in container:
TypeError: argument of type 'NoneType' is not iterable


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.TestUsers_1</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c2',1)">Detail</a></td>
</tr>

<tr id='ft2.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_user</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft2.1')" >
        error</a>

    <div id='div_ft2.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft2.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft2.1: --- Logging error ---
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 45, in get
    response = requests.get(self.url, headers=self.headers, params=self.data,
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 489, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 1085, in emit
    msg = self.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 929, in format
    return fmt.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 668, in format
    record.message = record.getMessage()
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "D:/Program Files/JetBrains/Projects/pythonProjects/interfaceTest/testCase/runAll.py", line 114, in &lt;module&gt;
    runner.run(suit)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\HTMLTestRunner.py", line 600, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\testCase\django_test\test_users.py", line 30, in test_user
    self.r = ch.get(self.case_name)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 50, in get
    logger.error('用例 %s 请求错误' % case_name, e)
Message: '用例 test_event_auth_ok 请求错误'
Arguments: (AttributeError("'str' object has no attribute 'items'"),)
--- Logging error ---
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 45, in get
    response = requests.get(self.url, headers=self.headers, params=self.data,
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 489, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 1085, in emit
    msg = self.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 929, in format
    return fmt.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 668, in format
    record.message = record.getMessage()
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "D:/Program Files/JetBrains/Projects/pythonProjects/interfaceTest/testCase/runAll.py", line 114, in &lt;module&gt;
    runner.run(suit)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\HTMLTestRunner.py", line 600, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\testCase\django_test\test_users.py", line 30, in test_user
    self.r = ch.get(self.case_name)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 50, in get
    logger.error('用例 %s 请求错误' % case_name, e)
Message: '用例 test_event_auth_ok 请求错误'
Arguments: (AttributeError("'str' object has no attribute 'items'"),)
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\testCase\django_test\test_users.py", line 31, in test_user
    self.assertIn(str(self.msg), self.r)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 1176, in assertIn
    if member not in container:
TypeError: argument of type 'NoneType' is not iterable


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.TestUsers_2</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c3',1)">Detail</a></td>
</tr>

<tr id='ft3.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_user</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.1')" >
        error</a>

    <div id='div_ft3.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.1: --- Logging error ---
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 45, in get
    response = requests.get(self.url, headers=self.headers, params=self.data,
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 489, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 1085, in emit
    msg = self.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 929, in format
    return fmt.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 668, in format
    record.message = record.getMessage()
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "D:/Program Files/JetBrains/Projects/pythonProjects/interfaceTest/testCase/runAll.py", line 114, in &lt;module&gt;
    runner.run(suit)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\HTMLTestRunner.py", line 600, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\testCase\django_test\test_users.py", line 30, in test_user
    self.r = ch.get(self.case_name)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 50, in get
    logger.error('用例 %s 请求错误' % case_name, e)
Message: '用例 test_guest_auth_null 请求错误'
Arguments: (AttributeError("'str' object has no attribute 'items'"),)
--- Logging error ---
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 45, in get
    response = requests.get(self.url, headers=self.headers, params=self.data,
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "D:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 489, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 1085, in emit
    msg = self.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 929, in format
    return fmt.format(record)
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 668, in format
    record.message = record.getMessage()
  File "D:\ProgramData\Miniconda3\lib\logging\__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "D:/Program Files/JetBrains/Projects/pythonProjects/interfaceTest/testCase/runAll.py", line 114, in &lt;module&gt;
    runner.run(suit)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\HTMLTestRunner.py", line 600, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\testCase\django_test\test_users.py", line 30, in test_user
    self.r = ch.get(self.case_name)
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\common\config_http.py", line 50, in get
    logger.error('用例 %s 请求错误' % case_name, e)
Message: '用例 test_guest_auth_null 请求错误'
Arguments: (AttributeError("'str' object has no attribute 'items'"),)
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\Projects\pythonProjects\interfaceTest\testCase\django_test\test_users.py", line 31, in test_user
    self.assertIn(str(self.msg), self.r)
  File "D:\ProgramData\Miniconda3\lib\unittest\case.py", line 1176, in assertIn
    if member not in container:
TypeError: argument of type 'NoneType' is not iterable


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='total_row'>
    <td>Total</td>
    <td>3</td>
    <td class="text text-success">0</td>
    <td class="text text-danger">0</td>
    <td class="text text-warning">3</td>
    <td>&nbsp;</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>

    <script type="text/javascript">
var data = [
	{
		value: 3,
		color: "#ebccd1",
		label: "Error",
		labelColor: 'white',
		labelFontSize: '16'
	},
	{
		value : 0,
		color : "#faebcc",
		label: "Fail",
		labelColor: 'white',
		labelFontSize: '16'
	},
	{
		value : 0,
		color : "#d6e9c6",
		label : "Pass",
		labelColor: 'white',
		labelFontSize: '16'
	}
]

var newopts = {
     animationSteps: 100,
 		animationEasing: 'easeInOutQuart',
}

//Get the context of the canvas element we want to select
var ctx = document.getElementById("myChart").getContext("2d");

var myNewChart = new Chart(ctx).Pie(data,newopts);

</script>
	
</body>
</template_pages>
